# Generated by Django 3.1.4 on 2021-06-14 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20210614_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prpoduct',
            new_name='Product',
        ),
    ]
